const BRAND_WHITE = '#FFFFFF';
const BRAND_BLACK = '#2D3653';

const DARK_BLUE_LOGO = '#1164C2';
const LIGHT_BLUE_LOGO = '#16C0F0';

export {DARK_BLUE_LOGO, LIGHT_BLUE_LOGO, BRAND_BLACK, BRAND_WHITE};
