const BRAND_WHITE = '#FFFFFF';
const BRAND_WHITE_OFF = '#EEEEEE';
const BRAND_WHITE_UNSELECTED = '#929292';
const BRAND_BLACK = '#2D3653';
const BRAND_BLACK_UNSELECTED = '#7F869F';
const BRAND_ORANGE = '#FFB053';
const BRAND_RED = '#ff5353';
const SYSTEM_BLUE = '#007AFF';

const LIGHT_OVERLAY = '#00000022';
const DARK_OVERLAY = '#00000044';
const VERY_DARK_OVERLAY = '#00000088';

const DARK_BLUE_LOGO = '#1164C2';
const LIGHT_BLUE_LOGO = '#16C0F0';

// Program Colors
// Breath
const BREATH_1_COLOR = '#5C6BC0';
const BREATH_2_COLOR = '#3F51B5';
const BREATH_3_COLOR = '#3949AB';
const BREATH_4_COLOR = '#303F9F';
const BREATH_5_COLOR = '#283593';
const BREATH_6_COLOR = '#1A237E';

// Hear
const HEAR_1_COLOR = '#43A047';
const HEAR_2_COLOR = '#388E3C';
const HEAR_3_COLOR = '#2E7D32';
const HEAR_4_COLOR = '#1B5E20';

// Sensationn
const SENSATION_1_COLOR = '#795548';
const SENSATION_2_COLOR = '#6D4C41';
const SENSATION_3_COLOR = '#5D4037';
const SENSATION_4_COLOR = '#4E342E';
const SENSATION_5_COLOR = '#3E2723';

export {
  DARK_BLUE_LOGO,
  LIGHT_BLUE_LOGO,
  SYSTEM_BLUE,
  BRAND_BLACK,
  BRAND_BLACK_UNSELECTED,
  BRAND_ORANGE,
  BRAND_RED,
  BRAND_WHITE,
  BRAND_WHITE_OFF,
  BRAND_WHITE_UNSELECTED,
  LIGHT_OVERLAY,
  DARK_OVERLAY,
  VERY_DARK_OVERLAY,
  BREATH_1_COLOR,
  BREATH_2_COLOR,
  BREATH_3_COLOR,
  BREATH_4_COLOR,
  BREATH_5_COLOR,
  BREATH_6_COLOR,
  HEAR_1_COLOR,
  HEAR_2_COLOR,
  HEAR_3_COLOR,
  HEAR_4_COLOR,
  SENSATION_1_COLOR,
  SENSATION_2_COLOR,
  SENSATION_3_COLOR,
  SENSATION_4_COLOR,
  SENSATION_5_COLOR,
};
