const BRAND_WHITE = '#FFFFFF';
const BRAND_BLACK = '#2D3653';
const SYSTEM_BLUE = '#007AFF';

const DARK_OVERLAY = '#2D365377';
const VERY_DARK_OVERLAY = '#2D365388';

const DARK_BLUE_LOGO = '#1164C2';
const LIGHT_BLUE_LOGO = '#16C0F0';

export {
  DARK_BLUE_LOGO,
  LIGHT_BLUE_LOGO,
  SYSTEM_BLUE,
  BRAND_BLACK,
  BRAND_WHITE,
  DARK_OVERLAY,
  VERY_DARK_OVERLAY,
};
