// SCREEN TYPES
const CLASS_SCREEN = 'class';
const ABOUT_SCREEN = 'about';
const ABOUT_CLASS_SCREEN = 'aboutClass';
const EXERCISE_SCREEN = 'exercise';
const ABOUT_EXERCISE_SCREEN = 'aboutExercise';

// EXERCISE SCREEN TYPES
const INSTRUCTION_EXERCISE_SCREEN = 'instruction';
const STANDARD_EXERCISE_SCREEN = 'exercise';

// EXERCISE METHOD TYPES
const BREATH_EXERCISE = 'Breath';
const SENSATION_EXERCISE = 'Sensation';
const THOUGHT_EXERCISE = 'Thought';
const HEAR_EXERCISE = 'Hear';
const SEE_EXERCISE = 'See';

const QUESTION_EXERCISE = 'Question';
const QUOTE_EXERCISE = 'Quote';
const INTERACTIVE_EXERCISE = 'Interactive';

// URL & LINKING
const URL_HEADER = 'practice://';

export {
  CLASS_SCREEN,
  ABOUT_SCREEN,
  ABOUT_CLASS_SCREEN,
  EXERCISE_SCREEN,
  ABOUT_EXERCISE_SCREEN,
  INSTRUCTION_EXERCISE_SCREEN,
  BREATH_EXERCISE,
  SENSATION_EXERCISE,
  THOUGHT_EXERCISE,
  HEAR_EXERCISE,
  SEE_EXERCISE,
  QUESTION_EXERCISE,
  QUOTE_EXERCISE,
  INTERACTIVE_EXERCISE,
  URL_HEADER,
};
