// SCREEN TYPES
const CLASS_SCREEN = 'class';
const ABOUT_SCREEN = 'about';
const ABOUT_CLASS_SCREEN = 'aboutClass';
const EXERCISE_SCREEN = 'exercise';
const ABOUT_EXERCISE_SCREEN = 'aboutExercise';

// EXERCISE SCREEN TYPES
const INSTRUCTION_EXERCISE_SCREEN = 'instruction';
const STANDARD_EXERCISE_SCREEN = 'exercise';

// EXERCISE METHOD TYPES
const BREATH_EXERCISE = 'breath';
const SENSATION_EXERCISE = 'sensation';
const THOUGHT_EXERCISE = 'thought';
const HEAR_EXERCISE = 'hear';

// URL & LINKING
const URL_HEADER = 'practice://';

export {
  CLASS_SCREEN,
  ABOUT_SCREEN,
  ABOUT_CLASS_SCREEN,
  EXERCISE_SCREEN,
  ABOUT_EXERCISE_SCREEN,
  INSTRUCTION_EXERCISE_SCREEN,
  BREATH_EXERCISE,
  SENSATION_EXERCISE,
  THOUGHT_EXERCISE,
  HEAR_EXERCISE,
  URL_HEADER,
};
