require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'SimpleNow' do
  use_unimodules!
  config = use_native_modules!

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  target 'SimpleNowTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SimpleNow-tvOS' do
  # Pods for SimpleNow-tvOS

  target 'SimpleNow-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
