// EXERCISE SCREEN TYPES
const INSTRUCTION_EXERCISE_SCREEN = 'instruction';

// EXERCISE METHOD TYPES
const BREATH_EXERCISE = 'breath';
const SENSATION_EXERCISE = 'sensation';
const THOUGHT_EXERCISE = 'thought';
const HEAR_EXERCISE = 'hear';
const SEE_EXERCISE = 'see';
const SENSE_EXERCISE = 'sense';
const SELF_AWARENESS_EXERCISE = 'awareness';
const QUESTION_EXERCISE = 'question';
const QUOTE_EXERCISE = 'quote';
const INTERACTIVE_EXERCISE = 'interactive';

// URL & LINKING
const URL_HEADER = 'simple-now://';

export {
  INSTRUCTION_EXERCISE_SCREEN,
  BREATH_EXERCISE,
  SENSATION_EXERCISE,
  THOUGHT_EXERCISE,
  HEAR_EXERCISE,
  SEE_EXERCISE,
  SENSE_EXERCISE,
  SELF_AWARENESS_EXERCISE,
  QUESTION_EXERCISE,
  QUOTE_EXERCISE,
  INTERACTIVE_EXERCISE,
  URL_HEADER,
};
